import React from 'react';
import Sidebar from '../components/Sidebar';
import Header from '../components/Header';

const sectionClass = 'legal-section';
const h2Class = 'legal-h2';
const pClass = 'legal-p';
const ulClass = 'legal-ul';

export default function Terms() {
  return (
    <div className="app-layout">
      <Sidebar />
      <main className="main-content">
        <Header title="Terms of Service" />
        <div className="page-content legal-page">
          <h1 className="legal-title">Terms of Service</h1>
          <p className="legal-updated">Last updated: June 2026</p>

          <section className={sectionClass}>
            <h2 className={h2Class}>1. Platform Description</h2>
            <p className={pClass}>
              VCL4X Engine (&quot;the Platform&quot;) is a software application that provides AI-powered market analytics,
              pattern recognition tools, and educational market research insights. The Platform analyzes market
              data, detects technical patterns, and delivers analytical observations for informational and
              educational purposes only.
            </p>
            <p className={pClass}>
              The Platform does NOT provide financial advice, investment recommendations, brokerage services,
              fund management, or trading instructions of any kind. All analytical outputs are generated by
              automated software and are intended solely as decision-support research tools.
            </p>
          </section>

          <section className={sectionClass}>
            <h2 className={h2Class}>2. What This Platform Is NOT</h2>
            <ul className={ulClass}>
              <li>Not a registered investment advisor or financial advisor</li>
              <li>Not a brokerage or trading platform</li>
              <li>Not a fund manager or asset manager</li>
              <li>Not a signal service providing investment recommendations</li>
              <li>Not responsible for any trading or investment decisions made by users</li>
              <li>Not guaranteeing any financial results, returns, or outcomes</li>
              <li>Not executing trades on behalf of users</li>
              <li>Not providing copy trading or managed account services</li>
            </ul>
          </section>

          <section className={sectionClass}>
            <h2 className={h2Class}>3. User Responsibilities</h2>
            <p className={pClass}>By using this Platform, you acknowledge and agree that:</p>
            <ul className={ulClass}>
              <li>You are solely responsible for all financial and investment decisions you make</li>
              <li>You will not rely on Platform outputs as financial or investment advice</li>
              <li>You understand that all market analysis involves inherent uncertainty and risk</li>
              <li>You have consulted or will consult with qualified financial professionals before making investment decisions</li>
              <li>You are of legal age to access financial information platforms in your jurisdiction</li>
              <li>You accept full responsibility for any financial losses incurred</li>
            </ul>
          </section>

          <section className={sectionClass}>
            <h2 className={h2Class}>4. Subscription &amp; Payment</h2>
            <p className={pClass}>
              Access to the Platform requires an active subscription. Subscriptions are billed on a monthly or
              annual basis. Payments are processed securely through Paddle. You may cancel your subscription
              at any time. Refunds are handled in accordance with our refund policy and applicable consumer
              protection laws in your jurisdiction.
            </p>
            <p className={pClass}>
              Subscription fees grant access to the Platform&apos;s analytical tools and research features only.
              Fees do not represent payment for financial advice, investment management, or brokerage services.
            </p>
          </section>

          <section className={sectionClass}>
            <h2 className={h2Class}>5. Intellectual Property</h2>
            <p className={pClass}>
              All analytical methodologies, algorithms, software, and content on this Platform are the
              exclusive intellectual property of VCL4X Engine. Users may not reproduce, distribute, reverse
              engineer, or commercially exploit any Platform content or methodology without written permission.
            </p>
          </section>

          <section className={sectionClass}>
            <h2 className={h2Class}>6. Risk Disclosure</h2>
            <p className={pClass}>
              Trading financial instruments including foreign exchange, commodities, and derivatives involves
              substantial risk of loss and is not suitable for all investors. Past analytical performance does
              not guarantee or predict future market behavior. You may lose some or all of your invested capital.
              You should not trade with money you cannot afford to lose.
            </p>
          </section>

          <section className={sectionClass}>
            <h2 className={h2Class}>7. Limitation of Liability</h2>
            <p className={pClass}>
              To the maximum extent permitted by applicable law, VCL4X Engine and its operators shall not be
              liable for any direct, indirect, incidental, consequential, or punitive damages arising from your
              use of the Platform or reliance on any analytical outputs. The Platform is provided &quot;as is&quot; without
              warranties of any kind.
            </p>
          </section>

          <section className={sectionClass}>
            <h2 className={h2Class}>8. Prohibited Uses</h2>
            <p className={pClass}>Users may not:</p>
            <ul className={ulClass}>
              <li>Redistribute or resell Platform analytical outputs</li>
              <li>Use Platform data to operate a competing signal or analytics service</li>
              <li>Attempt to reverse engineer or extract the underlying algorithms</li>
              <li>Share account credentials with unauthorized users</li>
              <li>Use the Platform in any jurisdiction where such services are prohibited</li>
            </ul>
          </section>

          <section className={sectionClass}>
            <h2 className={h2Class}>9. Modifications</h2>
            <p className={pClass}>
              We reserve the right to modify these Terms at any time. Continued use of the Platform after
              changes constitutes acceptance of the updated Terms. Material changes will be communicated
              via email or platform notification.
            </p>
          </section>

          <section className={sectionClass}>
            <h2 className={h2Class}>10. Contact</h2>
            <p className={pClass}>
              For questions regarding these Terms, contact us through the dashboard support system or
              via our Telegram community: @VCL4XAlphaAccess
            </p>
          </section>

          <div className="legal-disclaimer-box">
            <p className="legal-disclaimer-title">Important Disclaimer</p>
            <p className="legal-disclaimer-text">
              VCL4X Engine is a software platform that provides market analytics, research tools, and
              educational insights. The platform does not provide personalized financial advice, investment
              recommendations, or brokerage services. Users remain solely responsible for their own investment
              and trading decisions. All analytical outputs are generated by automated software for
              informational and educational purposes only.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
